package:
  name: assimulo
  version: !!str 2.8b1
  #version: trunk

source:
  fn: Assimulo-2.8b1-fix.zip
  url: https://pypi.python.org/packages/source/A/Assimulo/Assimulo-2.8b1-fix.zip
  #patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - assimulo = assimulo:main
    #
    # Would create an entry point called assimulo that calls assimulo.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - cython

  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  # Python imports
  imports:
    - assimulo
    - assimulo.examples
    - assimulo.lib
    - assimulo.solvers
    - assimulo.tests
    - assimulo.tests.solvers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL
  summary: 'A package for solving ordinary differential equations and differential algebraic equations.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
